#!/bin/bash
export MSYS_NO_PATHCONV=1
# Multiplatform approach to getting the dockerhost IP
export DOCKERHOST=${APPLICATION_URL-$(docker run --rm --net=host codenvy/che-ip)}
set -e

SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-indy-agentjs}"

export RUST_LOG=${RUST_LOG:-trace}

export TEST_POOL_IP=${TEST_POOL_IP:-DOCKERHOST}

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage () {
  cat <<-EOF

  Usage: $0 [command] [options]

  Commands:

  build - Build the docker images for the project.
          You need to do this first.

  start - Creates the application containers from the built images
          and starts the services based on the docker-compose.yml file.
          Examples - first starts both agents, starts only "alice"
          $0 start
          $0 start alice

  open - Opens the necessary browser tabs for all 5 of the services

  stop - Stops the services.  This is a non-destructive process.  The containers
         are not deleted so they will be reused the next time you run start.
         Ctrl-C can be used for this if in the same shell and script is in the foreground.

  rebuild - Rebuild the docker images - bypasses the docker image cache.

  rm - Remove project containers and any associated volumes (currently there are none).
EOF
exit 1
}
# -----------------------------------------------------------------------------------------------------------------
# Functions:
# -----------------------------------------------------------------------------------------------------------------
deleteVolumes() {
  echo "Stopping and removing any running containers ..."
  docker-compose rm -svf >/dev/null

  _projectName=${COMPOSE_PROJECT_NAME:-docker}

  _pattern="^${_projectName}_\|^docker_"
  _volumes=$(docker volume ls -q | grep ${_pattern})

  if [ ! -z "${_volumes}" ]; then
    echo "Removing project volumes ..."
    echo ${_volumes} |  xargs docker volume rm
  else
    echo "No project volumes exist."
  fi
}
# =================================================================================================================

pushd ${SCRIPT_HOME} >/dev/null

case "$1" in
  start)
      if [ -z "$2" ]; then
        SVCS='alice bob faber acme thrift'
      else
        shift
        SVCS="$@"
      fi
      docker-compose up ${SVCS}
    ;;
  open)
      if which open > /dev/null ; then
         OPEN=open
      elif which xdg-open > /dev/null ; then
         OPEN=xdg-open
      elif which gnome-open > /dev/null ; then
         OPEN=gnome-open
      else
         echo "Could not find a suitable tool to open your browser.\nYou will need to manually open 5 browser tabs for localhost:3000 through localhost:3004"
      fi
      $OPEN http://localhost:3000
      $OPEN http://localhost:3001
      $OPEN http://localhost:3002
      $OPEN http://localhost:3003
      $OPEN http://localhost:3004
    ;;
  stop)
      docker-compose stop
    ;;
  build)
      docker build -t indy-agentjs .
    ;;
  rebuild)
      docker-compose build --no-cache
    ;;
  rm)
      deleteVolumes
    ;;
  *)
      usage;;
esac

popd >/dev/null
